services:
  app:
    build: .
    container_name: office_robot_cleaner
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - LOAD_DOCKER_ENV=true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: test
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
