services:
  test-postgres:
    image: postgres:latest
    container_name: test_postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: database
